### ISSUE TITLE
times out on long replies

### ISSUE THREAD

**Issue by 0atman** [juanrgon/chatgpt-cli#1]
On very long replies the reqwest client times out with `source: TimedOut`. As openai api requests take longer if they are more complex, this will only affect big replies, and not short ones.

```
$ chatgpt write a 10 minute episode of monty python

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.openai.com")), port: None, path: "/v1/chat/completions", query: None, fragment: None }, source: TimedOut }', /home/oatman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chatgpt-cli-0.1
```

I think this could be fixed easily with finding out what kind of timeout it is and setting it to a large (over 1 minute) value https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.timeout

thanks!

**Comment by juanrgon** [comment]
This has been addressed in https://github.com/juanrgon/chatgpt-cli/pull/2
